version: '2.2'

services:
  freeswitch:
    image: "sapian/freeswitch"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
    restart: always
    network_mode: host
    tty: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "fs-volume:/config"
      - "fs-volume:/data"
      - "fs-volume:/sounds"
    environment:
      TZ: "America/Bogota"
volumes:
  fs-volume:
